name: DAST Scan

on:
  workflow_dispatch:
    inputs:
      target_url:
        description: "Cloud Run app URL to scan"
        required: true
        type: string

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.14.0
        with:
          target: ${{ inputs.target_url }}
          fail_action: false
          cmd_options: "-a"